name: pr test - new domain 

on:
  pull_request:
  workflow_dispatch: 

jobs:
  test-malicious-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Outbound call to domain
        run: |
          echo "Testing outbound connection to malicious-c2.com"
          curl -v http://google.com

      - name: Outbound call to bad domain
        run: |
          echo "Testing outbound connection to malicious-c2.com"
          curl -v http://malicious-c2.com
